// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for Android keystore (no secrets).
 */
export type AndroidKeystoreResponse = { id: string, repository_id: string, name: string, key_alias: string, keystore_type: string, is_active: boolean, created_at: string, };
