// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Android signing status for a repository.
 */
export type AndroidSigningStatus = { keystores_count: number, has_active_keystore: boolean, };
