// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for App Store Connect API key (no secrets).
 */
export type AppStoreConnectApiKeyResponse = { id: string, repository_id: string, name: string, key_id: string, 
/**
 * Masked issuer ID for display (shows first 8 and last 4 characters).
 */
issuer_id_masked: string, is_active: boolean, created_at: string, };
