// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API response DTO for build step.
 */
export type BuildStepResponse = { id: string, build_id: string, step_index: number, name: string, script: string | null, timeout_secs: number | null, ignore_failure: boolean, status: string, exit_code: number | null, started_at: string | null, finished_at: string | null, created_at: string, };
