// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for build artifact (for API).
 */
export type BuildArtifactResponse = { id: string, build_id: string, name: string, relative_path: string, size_bytes: number, content_type: string | null, checksum_sha256: string | null, created_at: string, 
/**
 * Download URL (relative).
 */
download_url: string, };
