// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API response DTO for build log metadata.
 */
export type BuildLogResponse = { id: string, build_id: string, step_index: number, stream: string, log_file_path: string, line_count: number, created_at: string, };
