// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response containing log content.
 */
export type BuildLogContentResponse = { step_index: number, stream: string, content: string, line_count: number, };
