// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API response DTO for build.
 */
export type BuildResponse = { id: string, repository_id: string, webhook_event_id: string | null, commit_sha: string, branch: string, trigger_type: string, status: string, started_at: string | null, finished_at: string | null, created_at: string, workflow_name: string | null, config_source: string | null, error_message: string | null, };
