// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Build status.
 */
export type BuildStatus = "pending" | "running" | "success" | "failure" | "cancelled";
