// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source of the pipeline configuration used for a build.
 */
export type ConfigSource = "repository" | "stored";
