// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoredConfigFormat } from "./StoredConfigFormat";

/**
 * Request to create/update a pipeline config.
 */
export type CreatePipelineConfigRequest = { name: string | null, config_content: string, config_format: StoredConfigFormat, };
