// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a new repository.
 */
export type CreateRepositoryRequest = { name: string | null, provider: string, owner: string, repo_name: string, clone_url: string | null, default_branch: string | null, 
/**
 * Plaintext webhook secret (will be hashed before storage).
 */
webhook_secret: string | null, github_repository_id: number | null, github_installation_id: number | null, gitlab_project_id: number | null, };
