// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DefaultPermissions = { contents: string, metadata: string, statuses: string, checks: string, };
