// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DefaultPermissions } from "./DefaultPermissions";
import type { HookAttributes } from "./HookAttributes";

/**
 * GitHub App manifest for creating a new app.
 */
export type GitHubAppManifest = { name: string, url: string, hook_attributes: HookAttributes, redirect_url: string, 
/**
 * URL to redirect users after they install the app
 */
setup_url: string, public: boolean, default_permissions: DefaultPermissions, default_events: Array<string>, };
