// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Setup status response for CLI polling.
 */
export type GitHubSetupStatusResponse = { 
/**
 * Status: "pending", "in_progress", "completed", "failed", "expired"
 */
status: string, 
/**
 * Human-readable message
 */
message: string, 
/**
 * App name (only when completed)
 */
app_name?: string, 
/**
 * App ID (only when completed)
 */
app_id?: number, 
/**
 * App slug for building installation URL (only when completed)
 */
app_slug?: string, };
