// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for GitHub App status.
 */
export type GitHubAppStatus = { configured: boolean, app_id?: number, app_name?: string, app_slug?: string, owner_login?: string, owner_type?: string, html_url?: string, installations_count: number, created_at?: string, };
