// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for GitLab credentials status.
 */
export type GitLabCredentialsStatus = { id: string, configured: boolean, instance_url?: string, username?: string, user_id?: number, token_expires_at?: string, needs_refresh: boolean, enabled_projects_count: number, };
