// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Project info for API response.
 */
export type GitLabProjectInfo = { id: number, name: string, path_with_namespace: string, web_url: string, visibility: string, default_branch?: string, ci_enabled: boolean, };
