// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Setup status response.
 */
export type GitLabSetupStatusResponse = { status: string, message: string, instance_url?: string, username?: string, };
