// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallationRepositoryInfo } from "./InstallationRepositoryInfo";

/**
 * Repositories response.
 */
export type InstallationRepositoriesResponse = { repositories: Array<InstallationRepositoryInfo>, };
