// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Repository info for installation.
 */
export type InstallationRepositoryInfo = { github_repository_id: number, full_name: string, is_private: boolean, };
