// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstallationInfo = { installation_id: number, account_login: string, account_type: string, repository_selection: string, is_active: boolean, };
