// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallationInfo } from "./InstallationInfo";

/**
 * Installation list response.
 */
export type InstallationsResponse = { installations: Array<InstallationInfo>, };
