// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for iOS certificate (no secrets).
 */
export type IosCertificateResponse = { id: string, repository_id: string, name: string, certificate_type: string, common_name: string | null, team_id: string | null, expires_at: string | null, is_active: boolean, created_at: string, };
