// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for iOS provisioning profile (no secrets).
 */
export type IosProfileResponse = { id: string, repository_id: string, name: string, profile_type: string, bundle_identifier: string | null, team_id: string | null, uuid: string, app_id_name: string | null, expires_at: string | null, is_active: boolean, created_at: string, };
