// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * iOS signing status for a repository.
 */
export type IosSigningStatus = { certificates_count: number, profiles_count: number, api_keys_count: number, has_active_certificate: boolean, has_active_profile: boolean, has_api_key: boolean, };
