// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitHubAppManifest } from "./GitHubAppManifest";

/**
 * Response for the manifest endpoint.
 */
export type ManifestResponse = { manifest: GitHubAppManifest, create_url: string, state: string, };
