// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoredConfigFormat } from "./StoredConfigFormat";

/**
 * API response DTO for pipeline config.
 */
export type PipelineConfigResponse = { id: string, repository_id: string, name: string, config_content: string, config_format: StoredConfigFormat, is_active: boolean, created_at: string, updated_at: string, };
