// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * iOS provisioning profile type.
 */
export type ProfileType = "development" | "adhoc" | "appstore" | "enterprise";
