// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API response DTO for repository (excludes secrets).
 */
export type RepositoryResponse = { id: string, name: string, provider: string, owner: string, repo_name: string, clone_url: string, default_branch: string, is_active: boolean, github_repository_id: number | null, github_installation_id: number | null, gitlab_project_id: number | null, created_at: string, updated_at: string, };
