// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitHubAppStatus } from "./GitHubAppStatus";
import type { GitLabCredentialsStatus } from "./GitLabCredentialsStatus";

/**
 * Combined setup status response.
 */
export type SetupStatusResponse = { github: GitHubAppStatus, gitlab: Array<GitLabCredentialsStatus>, encryption_configured: boolean, admin_token_configured: boolean, 
/**
 * Whether demo mode is enabled (all data is fake/simulated).
 */
demo_mode: boolean, };
