// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Setup response.
 */
export type SetupResponse = { auth_url: string, instance_url: string, state: string, };
