// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AndroidSigningStatus } from "./AndroidSigningStatus";
import type { IosSigningStatus } from "./IosSigningStatus";

/**
 * Combined signing status for a repository.
 */
export type SigningStatusResponse = { signing_enabled: boolean, ios: IosSigningStatus, android: AndroidSigningStatus, };
