// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a build step.
 */
export type StepStatus = "pending" | "running" | "success" | "failure" | "skipped" | "cancelled";
