// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to trigger a manual build.
 */
export type TriggerBuildRequest = { branch?: string, commit_sha?: string, };
