// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update a repository.
 */
export type UpdateRepositoryRequest = { name: string | null, default_branch: string | null, is_active: boolean | null, 
/**
 * New webhook secret (will be hashed before storage).
 */
webhook_secret: string | null, github_installation_id: number | null, gitlab_project_id: number | null, };
