// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to upload an iOS provisioning profile.
 */
export type UploadProfileRequest = { 
/**
 * Base64-encoded mobileprovision data.
 */
profile_data_base64: string, 
/**
 * Optional name (defaults to profile's app_id_name).
 */
name: string | null, };
