// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeystoreType } from "./KeystoreType";

/**
 * Request to upload an Android keystore.
 */
export type UploadKeystoreRequest = { name: string, 
/**
 * Base64-encoded keystore data.
 */
keystore_data_base64: string, keystore_password: string, key_alias: string, key_password: string, keystore_type: KeystoreType | null, };
