// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CertificateType } from "./CertificateType";

/**
 * Request to upload an iOS certificate.
 */
export type UploadCertificateRequest = { name: string, certificate_type: CertificateType, 
/**
 * Base64-encoded p12 data.
 */
certificate_data_base64: string, 
/**
 * Password for the p12 file.
 */
password: string, };
