// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to upload an App Store Connect API key.
 */
export type UploadApiKeyRequest = { name: string, 
/**
 * Apple's Key ID (10 alphanumeric characters).
 */
key_id: string, 
/**
 * Apple's Issuer ID (UUID).
 */
issuer_id: string, 
/**
 * Base64-encoded .p8 private key content.
 */
private_key_base64: string, };
