// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API response DTO for webhook event (excludes raw payload).
 */
export type WebhookEventResponse = { id: string, repository_id: string | null, provider: string, event_type: string, delivery_id: string, processed: boolean, error_message: string | null, received_at: string, };
