import { Resvg } from '@resvg/resvg-js'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import satori from 'satori'

const width = 1200
const height = 630
const repositoryRoot = path.resolve(import.meta.dir, '..')
const brandDir = path.join(repositoryRoot, 'shared/brand')

function asDataUri(mediaType: string, data: Buffer) {
  return `data:${mediaType};base64,${data.toString('base64')}`
}

const [regularFont, boldFont, logo, dashboard] = await Promise.all([
  readFile(path.join(brandDir, 'fonts/Inter-Regular.ttf')),
  readFile(path.join(brandDir, 'fonts/Inter-Bold.ttf')),
  readFile(path.join(brandDir, 'logo192.png')),
  readFile(
    path.join(repositoryRoot, 'apps/site/public/product/demo-dashboard.png'),
  ),
])

const svg = await satori(
  <div
    style={{
      alignItems: 'stretch',
      background: '#fafafa',
      color: '#171717',
      display: 'flex',
      fontFamily: 'Inter',
      height: '100%',
      overflow: 'hidden',
      position: 'relative',
      width: '100%',
    }}
  >
    <div
      style={{
        background: '#bb4d00',
        height: 10,
        left: 0,
        position: 'absolute',
        right: 0,
        top: 0,
      }}
    />
    <div
      style={{
        background:
          'radial-gradient(circle at center, rgba(187, 77, 0, 0.15), rgba(187, 77, 0, 0) 68%)',
        display: 'flex',
        height: 540,
        left: -160,
        position: 'absolute',
        top: -180,
        width: 540,
      }}
    />

    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        padding: '60px 0 52px 64px',
        width: 520,
      }}
    >
      <div style={{ alignItems: 'center', display: 'flex' }}>
        <img alt="" height={54} src={asDataUri('image/png', logo)} width={54} />
        <div
          style={{
            display: 'flex',
            fontSize: 26,
            fontWeight: 700,
            letterSpacing: '-0.04em',
            marginLeft: 14,
          }}
        >
          Oore CI
        </div>
      </div>

      <div
        style={{
          border: '1px solid #e5e5e5',
          color: '#525252',
          display: 'flex',
          fontSize: 16,
          marginTop: 58,
          padding: '8px 14px',
          width: 216,
        }}
      >
        Open-source mobile CI
      </div>

      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          fontSize: 62,
          fontWeight: 700,
          letterSpacing: '-0.055em',
          lineHeight: 1.02,
          marginTop: 24,
        }}
      >
        <span>Build on</span>
        <span style={{ color: '#bb4d00' }}>your own Mac.</span>
      </div>

      <div
        style={{
          color: '#525252',
          display: 'flex',
          fontSize: 22,
          lineHeight: 1.45,
          marginTop: 24,
          width: 430,
        }}
      >
        Build, sign, and distribute iOS and Android apps without giving up
        control.
      </div>

      <div
        style={{
          alignItems: 'center',
          color: '#737373',
          display: 'flex',
          fontSize: 18,
          marginTop: 'auto',
        }}
      >
        <span
          style={{
            background: '#bb4d00',
            display: 'flex',
            height: 8,
            marginRight: 12,
            width: 8,
          }}
        />
        oore.build
      </div>
    </div>

    <div
      style={{
        background: '#ffffff',
        border: '1px solid #d4d4d4',
        boxShadow: '0 24px 70px rgba(23, 23, 23, 0.16)',
        display: 'flex',
        height: 510,
        left: 548,
        overflow: 'hidden',
        position: 'absolute',
        top: 72,
        width: 760,
      }}
    >
      <img
        alt=""
        height={475}
        src={asDataUri('image/png', dashboard)}
        style={{
          height: 475,
          width: 760,
        }}
        width={760}
      />
    </div>
  </div>,
  {
    fonts: [
      {
        data: regularFont,
        name: 'Inter',
        style: 'normal',
        weight: 400,
      },
      {
        data: boldFont,
        name: 'Inter',
        style: 'normal',
        weight: 700,
      },
    ],
    height,
    width,
  },
)

const generatedSvg = `<!-- Generated by tools/generate-og-images.tsx. Edit the generator, not this file. -->\n${svg}\n`
const png = new Resvg(svg, {
  fitTo: { mode: 'width', value: width },
}).render()

await Promise.all([
  writeFile(path.join(brandDir, 'og-image.svg'), generatedSvg),
  writeFile(path.join(brandDir, 'og-image.png'), png.asPng()),
])

console.log(
  `Generated shared/brand/og-image.{svg,png} (${width}x${height}) with Satori`,
)
