[package]
name = "oore-contract"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
utoipa.workspace = true

[[bin]]
name = "openapi-export"
path = "src/bin/openapi_export.rs"
